textFormat
brief
briefmap
armplane
map ~bal2.T2
layer cloud1b.LAY 1
clouds 0
wind 65 7
view 1845 1041367 1695858
sides4 
	$80
	$0
	$80
	$80
	$0
	$80
	$80
	$0
	$0
	$80
	$0
	$0
	$80
	$0
	$80
	$80
	$0
	$0
	$0
	$0
	$0
	$0
	$0
	$0
	$80
	$0
	$0
	$0
	$0
	$0
	$0
	$80
	$0
	$80
	$0
	$80
	$0
	$80
	$0
	$0
	$0
	$80
	$0
	$0
	$0
	$0
	$0
	$0
	$0
	$0
	$0
	$0
	$80
	$80
	$80
	$0
	$0
	$80
	$0
	$80
	$0
	$0
	$0
	$0
time 12 0
usGroundSkill 1
usAirSkill 1
themGroundSkill 1
themAirSkill 1
historicalera 4
obj
	type KIEV.NT
	pos 500628 0 1931843
	angle -180 0 0
	nationality3 10
	flags $4413
	speed 0
	alias -1
	skill 2
	react $c000 $0 $0
	searchDist 0
	.
obj
	type CTOWR.OT
	pos 1195445 0 1694600
	angle -180 0 0
	nationality3 10
	flags $11
	speed 0
	alias -2
	.
obj
	type FUEL.OT
	pos 1204629 0 1689992
	angle 0 0 0
	nationality3 10
	flags $411
	speed 0
	alias -3
	.
obj
	type FUEL.OT
	pos 1204597 0 1690568
	angle 0 0 0
	nationality3 10
	flags $411
	speed 0
	alias -4
	.
obj
	type FUEL.OT
	pos 1204597 0 1691176
	angle 0 0 0
	nationality3 10
	flags $411
	speed 0
	alias -5
	.
obj
	type FUEL.OT
	pos 1204597 0 1691624
	angle 0 0 0
	nationality3 10
	flags $411
	speed 0
	alias -6
	.
obj
	type HANGRB.OT
	pos 721328 0 1657894
	angle 90 0 0
	nationality3 131
	flags $11
	speed 0
	alias -7
	.
obj
	type FUEL.OT
	pos 715197 0 1654128
	angle 0 0 0
	nationality3 131
	flags $411
	speed 0
	alias -8
	.
obj
	type DTSTRP.OT
	pos 877705 0 1645300
	angle -45 0 0
	nationality3 131
	flags $4413
	speed 0
	alias -9
	.
obj
	type BUNKER.OT
	pos 699759 0 1973986
	angle 0 0 0
	nationality3 10
	flags $411
	speed 0
	alias -10
	.
obj
	type BUNKER.OT
	pos 701199 0 1973986
	angle 0 0 0
	nationality3 10
	flags $411
	speed 0
	alias -11
	.
obj
	type FUEL.OT
	pos 704559 0 1969282
	angle 0 0 0
	nationality3 10
	flags $411
	speed 0
	alias -12
	.
obj
	type FUEL.OT
	pos 704431 0 1971586
	angle 0 0 0
	nationality3 10
	flags $411
	speed 0
	alias -13
	.
obj
	type TYPE69.NT
	pos 272538 0 1434177
	angle 90 0 0
	nationality3 131
	flags $13
	speed 0
	alias -14
	skill 1
	react $c000 $0 $0
	searchDist 0
	.
obj
	type KRIVAK.NT
	pos 469119 0 1921188
	angle -180 0 0
	nationality3 10
	flags $413
	speed 0
	alias -15
	skill 1
	react $c000 $0 $0
	searchDist 0
	.
obj
	type OLEKMA.NT
	pos 510743 0 1948582
	angle -180 0 0
	nationality3 10
	flags $413
	speed 0
	alias -16
	skill 1
	react $c000 $0 $0
	searchDist 0
	.
obj
	type SOVR.NT
	pos 483879 0 1878138
	angle -180 0 0
	nationality3 10
	flags $413
	speed 0
	alias -17
	skill 2
	react $c000 $0 $0
	searchDist 0
	.
obj
	type OLEKMA.NT
	pos 505002 0 1947762
	angle -180 0 0
	nationality3 10
	flags $413
	speed 0
	alias -18
	skill 1
	react $c000 $0 $0
	searchDist 0
	.
obj
	type OLEKMA.NT
	pos 510743 0 1955143
	angle -180 0 0
	nationality3 10
	flags $413
	speed 0
	alias -19
	skill 1
	react $c000 $0 $0
	searchDist 0
	.
obj
	type OLEKMA.NT
	pos 505002 0 1955143
	angle -180 0 0
	nationality3 10
	flags $413
	speed 0
	alias -20
	skill 1
	react $c000 $0 $0
	searchDist 0
	.
obj
	type KRIVAK.NT
	pos 456819 0 1954398
	angle -180 0 0
	nationality3 10
	flags $413
	speed 0
	alias -21
	skill 1
	react $c000 $0 $0
	searchDist 0
	.
obj
	type TYPE69.NT
	pos 331578 0 1511667
	angle 90 0 0
	nationality3 131
	flags $13
	speed 0
	alias -22
	skill 1
	react $c000 $0 $0
	searchDist 0
	.
obj
	type TICON.NT
	pos 290934 0 1477849
	angle 90 0 0
	nationality3 128
	flags $13
	speed 0
	alias -23
	skill 1
	react $c000 $0 $0
	searchDist 0
	.
obj
	type HANGR.OT
	pos 1200552 0 1691656
	angle -90 0 0
	nationality3 10
	flags $411
	speed 0
	alias -24
	.
obj
	type HANGR.OT
	pos 1200552 0 1690632
	angle -90 0 0
	nationality3 10
	flags $411
	speed 0
	alias -25
	.
obj
	type HANGR.OT
	pos 1201365 0 1689512
	angle -90 0 0
	nationality3 10
	flags $411
	speed 0
	alias -26
	.
obj
	type SA9.NT
	pos 1195765 0 1688040
	angle -135 0 0
	nationality3 10
	flags $413
	speed 0
	alias -27
	skill 1
	react $c000 $0 $0
	searchDist 0
	.
obj
	type FLAGY2.OT
	pos 1196485 0 1685748
	angle 0 0 0
	nationality3 10
	flags $411
	speed 0
	alias -28
	.
obj
	type SA15.NT
	pos 1201525 0 1692296
	angle 0 0 0
	nationality3 10
	flags $417
	speed 0
	alias -29
	skill 3
	react $c000 $0 $0
	searchDist 25
	.
obj
	type SA16.NT
	pos 1201493 0 1690088
	angle -90 0 0
	nationality3 10
	flags $413
	speed 0
	alias -30
	skill 1
	react $c000 $0 $0
	searchDist 0
	.
obj
	type STORE.OT
	pos 1200981 0 1695420
	angle -180 0 0
	nationality3 10
	flags $411
	speed 0
	alias -31
	.
obj
	type STORE.OT
	pos 1200245 0 1695420
	angle -180 0 0
	nationality3 10
	flags $411
	speed 0
	alias -32
	.
obj
	type TROOPS.NT
	pos 1201016 0 1695186
	angle 0 0 0
	nationality3 10
	flags $413
	speed 0
	alias -33
	skill 1
	react $c000 $0 $0
	searchDist 0
	.
obj
	type SFLUSH.NT
	pos 1203829 0 1695208
	angle -45 0 0
	nationality3 10
	flags $413
	speed 0
	alias -34
	skill 1
	react $c000 $0 $0
	searchDist 0
	.
obj
	type KING.OT
	pos 1199029 0 1692584
	angle 0 0 0
	nationality3 10
	flags $411
	speed 0
	alias -35
	.
obj
	type KING.OT
	pos 1194826 0 1692403
	angle 0 0 0
	nationality3 10
	flags $411
	speed 0
	alias -36
	.
obj
	type TRUCK.NT
	pos 1198293 0 1686728
	angle 0 0 0
	nationality3 10
	flags $417
	speed 0
	alias -37
	skill 1
	react $0 $0 $0
	searchDist 25
	.
obj
	type ZSU57.NT
	pos 1203445 0 1692680
	angle -135 0 0
	nationality3 10
	flags $413
	speed 0
	alias -38
	skill 1
	react $c000 $0 $0
	searchDist 0
	.
obj
	type BMP2.NT
	pos 1196661 0 1694632
	angle -90 0 0
	nationality3 10
	flags $413
	speed 0
	alias -39
	skill 2
	react $c000 $3fff $0
	searchDist 0
	.
obj
	type BTR80.NT
	pos 1204215 0 1688024
	angle 0 0 0
	nationality3 10
	flags $417
	speed 0
	alias -40
	skill 3
	react $c000 $0 $0
	searchDist 25
	.
obj
	type 2S6.NT
	pos 1194741 0 1693352
	angle -90 0 0
	nationality3 10
	flags $413
	speed 0
	alias -41
	skill 3
	react $c000 $0 $0
	searchDist 0
	.
obj
	type MTCAMO.OT
	pos 717616 0 1659782
	angle 0 0 0
	nationality3 131
	flags $411
	speed 0
	alias -42
	.
obj
	type MTCAMO.OT
	pos 718288 0 1659750
	angle 0 0 0
	nationality3 131
	flags $411
	speed 0
	alias -43
	.
obj
	type MTCAMO.OT
	pos 719024 0 1659750
	angle 0 0 0
	nationality3 131
	flags $411
	speed 0
	alias -44
	.
obj
	type GAZ.PT
	pos 714870 0 1655567
	angle 0 0 0
	nationality3 131
	flags $4417
	speed 0
	alias -45
	skill 1
	react $0 $ffff $0
	searchDist 0
	startTime 1800
	.
obj
	type GAZ.PT
	pos 720505 0 1660976
	angle 89 0 0
	nationality3 131
	flags $4417
	speed 0
	alias -46
	skill 1
	react $0 $ffff $0
	searchDist 0
	startTime 600
	.
obj
	type SFR.PT
	pos 718117 0 1660190
	angle 89 0 0
	nationality3 131
	flags $4417
	speed 0
	alias -47
	skill 1
	react $0 $ffff $0
	searchDist 0
	startTime 1080
	.
obj
	type TENT1.OT
	pos 717565 0 1656528
	angle 0 0 0
	nationality3 131
	flags $411
	speed 0
	alias -48
	.
obj
	type TENT1.OT
	pos 717597 0 1657040
	angle 0 0 0
	nationality3 131
	flags $411
	speed 0
	alias -49
	.
obj
	type TENT1.OT
	pos 717629 0 1657520
	angle 0 0 0
	nationality3 131
	flags $411
	speed 0
	alias -50
	.
obj
	type CMHQ1.OT
	pos 716285 0 1657456
	angle 0 0 0
	nationality3 131
	flags $411
	speed 0
	alias -51
	.
obj
	type TOWER.OT
	pos 712349 0 1656432
	angle -90 0 0
	nationality3 131
	flags $411
	speed 0
	alias -52
	.
obj
	type ASA5.NT
	pos 717757 0 1658480
	angle 90 0 0
	nationality3 131
	flags $413
	speed 0
	alias -53
	skill 0
	react $0 $c000 $0
	searchDist 0
	.
obj
	type ASA5.NT
	pos 720317 0 1656336
	angle 90 0 0
	nationality3 131
	flags $413
	speed 0
	alias -54
	skill 0
	react $0 $c000 $0
	searchDist 0
	.
obj
	type TRUCK.NT
	pos 720413 0 1657072
	angle 0 0 0
	nationality3 131
	flags $413
	speed 0
	alias -55
	skill 1
	react $c000 $0 $0
	searchDist 0
	.
obj
	type TRUCK.NT
	pos 720413 0 1657424
	angle 0 0 0
	nationality3 131
	flags $413
	speed 0
	alias -56
	skill 1
	react $0 $c000 $0
	searchDist 0
	.
obj
	type M113.NT
	pos 718749 0 1657136
	angle 0 0 0
	nationality3 131
	flags $413
	speed 0
	alias -57
	skill 1
	react $c000 $3fff $0
	searchDist 0
	.
obj
	type M113.NT
	pos 718749 0 1657808
	angle -90 0 0
	nationality3 131
	flags $413
	speed 0
	alias -58
	skill 1
	react $c000 $3fff $0
	searchDist 0
	.
obj
	type TENT1.OT
	pos 880009 0 1647876
	angle 0 0 0
	nationality3 143
	flags $11
	speed 0
	alias -59
	.
obj
	type TENT1.OT
	pos 880745 0 1647828
	angle 0 0 0
	nationality3 143
	flags $11
	speed 0
	alias -60
	.
obj
	type TENT1.OT
	pos 879977 0 1647284
	angle 0 0 0
	nationality3 143
	flags $11
	speed 0
	alias -61
	.
obj
	type TENT1.OT
	pos 880681 0 1647284
	angle 0 0 0
	nationality3 143
	flags $11
	speed 0
	alias -62
	.
obj
	type TENT1.OT
	pos 882057 0 1647764
	angle 0 0 0
	nationality3 143
	flags $11
	speed 0
	alias -63
	.
obj
	type TENT1.OT
	pos 881353 0 1647796
	angle 0 0 0
	nationality3 143
	flags $411
	speed 0
	alias -64
	.
obj
	type TENT1.OT
	pos 881385 0 1647252
	angle 0 0 0
	nationality3 143
	flags $11
	speed 0
	alias -65
	.
obj
	type TENT1.OT
	pos 882153 0 1647220
	angle 0 0 0
	nationality3 143
	flags $11
	speed 0
	alias -66
	.
obj
	type TENT1.OT
	pos 879977 0 1648404
	angle 0 0 0
	nationality3 143
	flags $491
	speed 0
	alias -67
	.
obj
	type TENT1.OT
	pos 880713 0 1648404
	angle 0 0 0
	nationality3 143
	flags $491
	speed 0
	alias -68
	.
obj
	type TENT1.OT
	pos 881417 0 1648404
	angle 0 0 0
	nationality3 143
	flags $491
	speed 0
	alias -69
	.
obj
	type TENT1.OT
	pos 882057 0 1648372
	angle 0 0 0
	nationality3 143
	flags $91
	speed 0
	alias -70
	.
obj
	type MTCAMO.OT
	pos 879977 0 1649044
	angle 0 0 0
	nationality3 143
	flags $491
	speed 0
	alias -71
	.
obj
	type MTCAMO.OT
	pos 880681 0 1649012
	angle 0 0 0
	nationality3 143
	flags $491
	speed 0
	alias -72
	.
obj
	type MTCAMO.OT
	pos 879977 0 1649652
	angle 0 0 0
	nationality3 143
	flags $491
	speed 0
	alias -73
	.
obj
	type MTCAMO.OT
	pos 880713 0 1649620
	angle 0 0 0
	nationality3 143
	flags $491
	speed 0
	alias -74
	.
obj
	type TENT1.OT
	pos 879945 0 1650324
	angle 0 0 0
	nationality3 143
	flags $491
	speed 0
	alias -75
	.
obj
	type TENT1.OT
	pos 880681 0 1650324
	angle 0 0 0
	nationality3 143
	flags $491
	speed 0
	alias -76
	.
obj
	type TENT1.OT
	pos 881417 0 1650228
	angle 0 0 0
	nationality3 143
	flags $491
	speed 0
	alias -77
	.
obj
	type TENT1.OT
	pos 882153 0 1650164
	angle 0 0 0
	nationality3 143
	flags $491
	speed 0
	alias -78
	.
obj
	type TENT1.OT
	pos 882825 0 1650100
	angle 0 0 0
	nationality3 143
	flags $491
	speed 0
	alias -79
	.
obj
	type TRUCK.NT
	pos 881513 0 1649588
	angle -45 0 0
	nationality3 143
	flags $493
	speed 0
	alias -80
	skill 1
	react $c000 $0 $0
	searchDist 0
	.
obj
	type TRUCK.NT
	pos 882153 0 1650228
	angle -45 0 0
	nationality3 143
	flags $493
	speed 0
	alias -81
	skill 1
	react $c000 $0 $0
	searchDist 0
	.
obj
	type TRUCK.NT
	pos 880073 0 1650036
	angle -90 0 0
	nationality3 143
	flags $493
	speed 0
	alias -82
	skill 1
	react $c000 $0 $0
	searchDist 0
	.
obj
	type TRUCK.NT
	pos 879305 0 1649428
	angle -180 0 0
	nationality3 143
	flags $493
	speed 0
	alias -83
	skill 0
	react $c000 $0 $0
	searchDist 0
	.
obj
	type TRUCK.NT
	pos 881577 0 1646708
	angle -45 0 0
	nationality3 143
	flags $493
	speed 0
	alias -84
	skill 0
	react $c000 $0 $0
	searchDist 0
	.
obj
	type TRUCK.NT
	pos 882825 0 1648276
	angle -45 0 0
	nationality3 143
	flags $493
	speed 0
	alias -85
	skill 1
	react $c000 $0 $0
	searchDist 0
	.
obj
	type TRUCK.NT
	pos 883497 0 1648436
	angle -45 0 0
	nationality3 143
	flags $493
	speed 0
	alias -86
	skill 0
	react $c000 $0 $0
	searchDist 0
	.
obj
	type RUNNER.NT
	pos 880265 0 1646676
	angle 0 0 0
	nationality3 143
	flags $417
	speed 0
	alias -87
	skill 1
	react $0 $0 $0
	searchDist 25
	.
obj
	type MICROM.OT
	pos 884105 0 1646900
	angle 0 0 0
	nationality3 143
	flags $411
	speed 0
	alias -88
	.
obj
	type M113.NT
	pos 882281 0 1644948
	angle 0 0 0
	nationality3 131
	flags $413
	speed 0
	alias -89
	skill 0
	react $0 $ffff $0
	searchDist 0
	.
obj
	type M113.NT
	pos 880745 0 1644948
	angle 0 0 0
	nationality3 131
	flags $413
	speed 0
	alias -90
	skill 1
	react $0 $ffff $0
	searchDist 0
	.
obj
	type M113.NT
	pos 876745 0 1646260
	angle -45 0 0
	nationality3 131
	flags $413
	speed 0
	alias -91
	skill 0
	react $0 $ffff $0
	searchDist 0
	.
obj
	type TENT1.OT
	pos 878313 0 1645268
	angle -45 0 0
	nationality3 131
	flags $411
	speed 0
	alias -92
	.
obj
	type MTCAMO.OT
	pos 876969 0 1645044
	angle 0 0 0
	nationality3 131
	flags $411
	speed 0
	alias -93
	.
obj
	type SFR.PT
	pos 878038 0 1644969
	angle -45 0 0
	nationality3 131
	flags $4417
	speed 0
	alias -94
	skill 1
	react $0 $ffff $0
	searchDist 0
	startTime 1800
	.
obj
	type TROOPS.NT
	pos 880105 0 1647732
	angle 0 0 0
	nationality3 143
	flags $493
	speed 0
	alias -95
	skill 0
	react $c000 $0 $0
	searchDist 0
	.
obj
	type TROOPS.NT
	pos 880745 0 1648372
	angle 0 0 0
	nationality3 143
	flags $493
	speed 0
	alias -96
	skill 0
	react $c000 $0 $0
	searchDist 0
	.
obj
	type TROOPS.NT
	pos 881385 0 1649012
	angle 0 0 0
	nationality3 143
	flags $493
	speed 0
	alias -97
	skill 1
	react $c000 $0 $0
	searchDist 0
	.
obj
	type TROOPS.NT
	pos 882025 0 1649652
	angle 0 0 0
	nationality3 143
	flags $493
	speed 0
	alias -98
	skill 1
	react $c000 $0 $0
	searchDist 0
	.
obj
	type TROOPS.NT
	pos 882665 0 1650292
	angle 0 0 0
	nationality3 143
	flags $493
	speed 0
	alias -99
	skill 0
	react $c000 $0 $0
	searchDist 0
	.
obj
	type TROOPS.NT
	pos 881321 0 1648372
	angle 135 0 0
	nationality3 143
	flags $493
	speed 0
	alias -100
	skill 1
	react $c000 $0 $0
	searchDist 0
	.
obj
	type TROOPS.NT
	pos 881993 0 1648788
	angle 135 0 0
	nationality3 143
	flags $493
	speed 0
	alias -101
	skill 1
	react $c000 $0 $0
	searchDist 0
	.
obj
	type TROOPS.NT
	pos 880745 0 1649940
	angle 135 0 0
	nationality3 143
	flags $493
	speed 0
	alias -102
	skill 1
	react $c000 $0 $0
	searchDist 0
	.
obj
	type TROOPS.NT
	pos 881417 0 1647796
	angle 135 0 0
	nationality3 143
	flags $493
	speed 0
	alias -103
	skill 0
	react $c000 $0 $0
	searchDist 0
	.
obj
	type SA7.NT
	pos 881385 0 1650388
	angle 45 0 0
	nationality3 143
	flags $493
	speed 0
	alias -104
	skill 3
	react $c000 $0 $0
	searchDist 0
	.
obj
	type TRUCK.NT
	pos 882409 0 1647412
	angle -45 0 0
	nationality3 143
	flags $93
	speed 0
	alias -105
	skill 0
	react $c000 $0 $0
	searchDist 0
	.
obj
	type SA7.NT
	pos 880873 0 1647572
	angle 45 0 0
	nationality3 143
	flags $493
	speed 0
	alias -106
	skill 1
	react $c000 $0 $0
	searchDist 0
	.
obj
	type HUMVEE.NT
	pos 881513 0 1648212
	angle 0 0 0
	nationality3 131
	flags $413
	speed 0
	alias -107
	skill 0
	react $0 $c000 $0
	searchDist 0
	.
obj
	type CROPA.OT
	pos 883913 0 1651540
	angle 0 0 0
	nationality3 143
	flags $411
	speed 0
	alias -108
	.
obj
	type CROPB.OT
	pos 879081 0 1652212
	angle 0 0 0
	nationality3 143
	flags $411
	speed 0
	alias -109
	.
obj
	type CRATE1.OT
	pos 880905 0 1648660
	angle 0 0 0
	nationality3 143
	flags $491
	speed 0
	alias -110
	.
obj
	type CRATE2.OT
	pos 881545 0 1649300
	angle 0 0 0
	nationality3 143
	flags $491
	speed 0
	alias -111
	.
obj
	type CRATE3.OT
	pos 882185 0 1649940
	angle -90 0 0
	nationality3 143
	flags $491
	speed 0
	alias -112
	.
obj
	type CRATE4.OT
	pos 880009 0 1649300
	angle 0 0 0
	nationality3 143
	flags $491
	speed 0
	alias -113
	.
obj
	type CONT1.OT
	pos 880649 0 1649940
	angle 0 0 0
	nationality3 143
	flags $491
	speed 0
	alias -114
	.
obj
	type CONT2.OT
	pos 880905 0 1647316
	angle 0 0 0
	nationality3 143
	flags $411
	speed 0
	alias -115
	.
obj
	type BNK4.OT
	pos 701327 0 1969794
	angle -90 0 0
	nationality3 10
	flags $411
	speed 0
	alias -116
	.
obj
	type BNK4.OT
	pos 704431 0 1970338
	angle 90 0 0
	nationality3 10
	flags $411
	speed 0
	alias -117
	.
obj
	type BARKSA.OT
	pos 699791 0 1970978
	angle -45 0 0
	nationality3 10
	flags $411
	speed 0
	alias -118
	.
obj
	type TOWER.OT
	pos 699119 0 1972290
	angle 0 0 0
	nationality3 10
	flags $411
	speed 0
	alias -119
	.
obj
	type TRUCK.NT
	pos 700943 0 1970850
	angle -135 0 0
	nationality3 10
	flags $413
	speed 0
	alias -120
	skill 1
	react $c000 $0 $0
	searchDist 0
	.
obj
	type MI24.PT
	pos 1198116 0 1688337
	angle 0 0 0
	nationality3 10
	flags $4417
	speed 0
	alias -121
	skill 1
	react $c000 $0 $0
	searchDist 25
	wing 7 0
	wng 1 0 2048 0
	.
obj
	type SU25.PT
	pos 1203751 0 1693746
	angle 89 0 0
	nationality3 10
	flags $4017
	speed 0
	alias -122
	controller $80
	name Player
	skill 2
	react $c000 $0 $0
	searchDist 25
	wing 0 0
	wng 2 0 2048 0
	.
obj
	type SU25.PT
	pos 1201363 0 1692960
	angle 89 0 0
	nationality3 10
	flags $4417
	speed 0
	alias -123
	skill 1
	react $c000 $0 $0
	searchDist 25
	npcFlags 2
	wing 0 1
	wng 2 0 2048 0
	.
obj
	type MIG23.PT
	pos 1203751 0 1692170
	angle 89 0 0
	nationality3 10
	flags $4417
	speed 0
	alias -124
	skill 0
	react $c000 $3fff $0
	searchDist 0
	startTime 3120
	wing 6 0
	wng 1 1 2048 0
	.
obj
	type MIG23.PT
	pos 1201363 0 1690599
	angle 89 0 0
	nationality3 10
	flags $4417
	speed 0
	alias -125
	skill 2
	react $c000 $3fff $0
	searchDist 0
	startTime 3120
	wing 6 3
	wng 1 1 2048 0
	.
obj
	type MIG23.PT
	pos 1203751 0 1691387
	angle 89 0 0
	nationality3 10
	flags $4417
	speed 0
	alias -126
	skill 0
	react $c000 $3fff $0
	searchDist 0
	startTime 3120
	wing 6 2
	wng 1 1 2048 0
	.
obj
	type MIG23.PT
	pos 1201363 0 1691387
	angle 89 0 0
	nationality3 10
	flags $4417
	speed 0
	alias -127
	skill 2
	react $c000 $3fff $0
	searchDist 0
	startTime 3120
	wing 6 1
	wng 1 1 2048 0
	.
obj
	type IL96.PT
	pos 1479433 26000 1520065
	angle -45 0 0
	nationality3 10
	flags $4017
	speed 457
	alias -128
	skill 2
	react $0 $0 $c000
	searchDist 25
	.
obj
	type SA3SITE.OT
	pos 996332 0 1694349
	angle 0 0 0
	nationality3 10
	flags $411
	speed 0
	alias -129
	.
obj
	type SA3.NT
	pos 996332 0 1695085
	angle 0 0 0
	nationality3 10
	flags $413
	speed 0
	alias -130
	skill 1
	react $c000 $0 $0
	searchDist 0
	.
obj
	type SA3.NT
	pos 997004 0 1693933
	angle -180 0 0
	nationality3 10
	flags $413
	speed 0
	alias -131
	skill 1
	react $c000 $0 $0
	searchDist 0
	.
obj
	type SA3.NT
	pos 995692 0 1693933
	angle -135 0 0
	nationality3 10
	flags $413
	speed 0
	alias -132
	skill 1
	react $c000 $0 $0
	searchDist 0
	.
obj
	type SU25.PT
	pos 1203751 0 1692960
	angle 89 0 0
	nationality3 10
	flags $4417
	speed 0
	alias -133
	skill 2
	react $c000 $0 $0
	searchDist 25
	npcFlags 2
	wing 0 2
	wng 2 0 2048 0
	.
obj
	type SU25.PT
	pos 1201363 0 1692170
	angle 89 0 0
	nationality3 10
	flags $4417
	speed 0
	alias -134
	skill 1
	react $c000 $0 $0
	searchDist 25
	npcFlags 2
	wing 0 3
	wng 2 0 2048 0
	.
obj
	type T72.NT
	pos 1052346 0 1632973
	angle -44 0 0
	nationality3 19
	flags $417
	speed 0
	alias -135
	skill 3
	react $3fff $c000 $0
	preferredTargetId2 $ff76
	searchDist 10
	.
obj
	type T72.NT
	pos 1056953 0 1627070
	angle -44 0 0
	nationality3 19
	flags $417
	speed 0
	alias -136
	skill 2
	react $ffff $0 $0
	preferredTargetId2 $ff76
	searchDist 10
	.
obj
	type T72.NT
	pos 1055657 0 1634269
	angle -44 0 0
	nationality3 19
	flags $417
	speed 0
	alias -137
	skill 2
	react $3fff $c000 $0
	searchDist 10
	.
obj
	type T72.NT
	pos 1051554 0 1636141
	angle 135 0 0
	nationality3 143
	flags $417
	speed 0
	alias -138
	skill 1
	react $ffff $0 $0
	preferredTargetId2 $ff79
	searchDist 10
	.
obj
	type T72.NT
	pos 1055729 0 1638588
	angle 135 0 0
	nationality3 143
	flags $417
	speed 0
	alias -139
	skill 0
	react $ffff $0 $0
	searchDist 10
	.
obj
	type T80.NT
	pos 1061776 0 1628654
	angle 0 0 0
	nationality3 19
	flags $417
	speed 0
	alias -140
	skill 3
	react $3fff $c000 $0
	preferredTargetId2 $ff75
	searchDist 10
	.
obj
	type BTR80.NT
	pos 1047379 0 1640532
	angle -135 0 0
	nationality3 143
	flags $417
	speed 0
	alias -141
	skill 1
	react $c000 $0 $0
	preferredTargetId2 $ff78
	searchDist 25
	.
obj
	type BTR80.NT
	pos 1049251 0 1641035
	angle -135 0 0
	nationality3 143
	flags $417
	speed 0
	alias -142
	skill 1
	react $c000 $0 $0
	preferredTargetId2 $ff79
	searchDist 25
	.
obj
	type BTR80.NT
	pos 1052058 0 1641035
	angle -135 0 0
	nationality3 143
	flags $417
	speed 0
	alias -143
	skill 1
	react $c000 $0 $0
	preferredTargetId2 $ff77
	searchDist 25
	.
obj
	type SA7.NT
	pos 1050762 0 1640891
	angle 135 0 0
	nationality3 143
	flags $413
	speed 0
	alias -144
	skill 2
	react $c000 $0 $0
	searchDist 0
	.
obj
	type SA7.NT
	pos 1054217 0 1639164
	angle 135 0 0
	nationality3 143
	flags $413
	speed 0
	alias -145
	skill 1
	react $c000 $0 $0
	searchDist 0
	.
obj
	type ZSU57.NT
	pos 1055801 0 1625055
	angle 0 0 0
	nationality3 19
	flags $413
	speed 0
	alias -146
	skill 1
	react $c000 $0 $0
	searchDist 0
	.
obj
	type ZSU57.NT
	pos 1064367 0 1628870
	angle 0 0 0
	nationality3 19
	flags $413
	speed 0
	alias -147
	skill 2
	react $c000 $0 $0
	searchDist 0
	.
obj
	type SA9.NT
	pos 1060048 0 1625991
	angle 0 0 0
	nationality3 19
	flags $413
	speed 0
	alias -148
	skill 0
	react $c000 $0 $0
	searchDist 0
	.
obj
	type SA9.NT
	pos 1062784 0 1626135
	angle 0 0 0
	nationality3 19
	flags $413
	speed 0
	alias -149
	skill 2
	react $c000 $0 $0
	searchDist 0
	.
obj
	type YAK141.PT
	pos 500726 0 1932860
	angle 175 0 0
	nationality3 10
	flags $4417
	speed 0
	alias -150
	skill 1
	react $c000 $3fff $0
	searchDist 0
	startTime 3000
	.
obj
	type YAK141.PT
	pos 500532 0 1932931
	angle 90 0 0
	nationality3 10
	flags $4417
	speed 0
	alias -151
	skill 1
	react $c000 $3fff $0
	searchDist 0
	.
obj
	type YAK141.PT
	pos 500476 0 1932791
	angle 90 0 0
	nationality3 10
	flags $4417
	speed 0
	alias -152
	skill 1
	react $c000 $3fff $0
	searchDist 0
	.
obj
	type YAK141.PT
	pos 500478 0 1932679
	angle 90 0 0
	nationality3 10
	flags $4417
	speed 0
	alias -153
	skill 1
	react $c000 $3fff $0
	searchDist 0
	.
obj
	type BTR80.NT
	pos 1203208 0 1691189
	angle -180 0 0
	nationality3 10
	flags $417
	speed 0
	alias -154
	skill 1
	react $c000 $0 $0
	searchDist 25
	.
waypoint2 4
	w_index 0
	w_flags $1
	w_goal 0
	w_next 0
	w_pos2 0   0   1201525 0 1692296
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

	w_index 1
	w_flags $4
	w_goal 1
	w_next 0
	w_pos2 1   0   1202165 0 1692936
	w_speed 16
	w_wng 1 0 2048 0
	w_react $c000 $0 $0
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name 

	w_index 2
	w_flags $4
	w_goal 1
	w_next 0
	w_pos2 1   0   1199861 0 1691304
	w_speed 16
	w_wng 1 0 2048 0
	w_react $c000 $0 $0
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name 

	w_index 3
	w_flags $2
	w_goal 0
	w_next 0
	w_pos2 0   0   0 0 0
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

  w_for -29
	.

waypoint2 4
	w_index 0
	w_flags $1
	w_goal 0
	w_next 0
	w_pos2 0   0   1198293 0 1686728
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

	w_index 1
	w_flags $4
	w_goal 1
	w_next 0
	w_pos2 1   0   1198485 0 1693032
	w_speed 16
	w_wng 1 0 2048 0
	w_react $c000 $0 $0
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name 

	w_index 2
	w_flags $4
	w_goal 1
	w_next 0
	w_pos2 1   0   1201352 0 1694389
	w_speed 16
	w_wng 1 0 2048 0
	w_react $c000 $0 $0
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name 

	w_index 3
	w_flags $2
	w_goal 0
	w_next 0
	w_pos2 0   0   0 0 0
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

  w_for -37
	.

waypoint2 3
	w_index 0
	w_flags $1
	w_goal 0
	w_next 0
	w_pos2 0   0   1204215 0 1688024
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

	w_index 1
	w_flags $4
	w_goal 1
	w_next 0
	w_pos2 1   0   1204597 0 1695240
	w_speed 33
	w_wng 1 0 2048 0
	w_react $c000 $0 $0
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name 

	w_index 2
	w_flags $2
	w_goal 0
	w_next 0
	w_pos2 0   0   0 0 0
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

  w_for -40
	.

waypoint2 3
	w_index 0
	w_flags $1
	w_goal 0
	w_next 0
	w_pos2 0   0   880265 0 1646676
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

	w_index 1
	w_flags $4
	w_goal 1
	w_next 0
	w_pos2 1   0   881225 0 1651188
	w_speed 10
	w_wng 1 0 2048 0
	w_react $c000 $0 $0
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name 

	w_index 2
	w_flags $2
	w_goal 0
	w_next 0
	w_pos2 0   0   0 0 0
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

  w_for -87
	.

waypoint2 8
	w_index 0
	w_flags $1
	w_goal 0
	w_next 0
	w_pos2 0   0   1198116 0 1688337
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

	w_index 1
	w_flags $0
	w_goal 34
	w_next 0
	w_pos2 1   0   1198229 0 1694216
	w_speed 84
	w_wng 1 0 2048 0
	w_react $c000 $0 $0
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name 

	w_index 2
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 1   0   1198389 1000 1695336
	w_speed 84
	w_wng 1 0 2048 0
	w_react $c000 $0 $0
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name 

	w_index 3
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 1   0   1206741 1000 1695720
	w_speed 84
	w_wng 1 0 2048 0
	w_react $c000 $0 $0
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name 

	w_index 4
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 1   0   1207845 1000 1686744
	w_speed 84
	w_wng 1 0 2048 0
	w_react $c000 $0 $0
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name 

	w_index 5
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 1   0   1198341 1000 1684536
	w_speed 84
	w_wng 1 0 2048 0
	w_react $c000 $0 $0
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name 

	w_index 6
	w_flags $0
	w_goal 34
	w_next 0
	w_pos2 1   0   1198965 0 1687704
	w_speed 84
	w_wng 1 0 2048 0
	w_react $c000 $0 $0
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name LAnd

	w_index 7
	w_flags $2
	w_goal 0
	w_next 0
	w_pos2 0   0   0 0 0
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

  w_for -121
	.

waypoint2 10
	w_index 0
	w_flags $1
	w_goal 0
	w_next 0
	w_pos2 0   0   1203751 0 1693746
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

	w_index 1
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 1   0   1197051 3000 1703642
	w_speed 590
	w_wng 2 0 2048 0
	w_react $c000 $0 $0
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name Take-Off

	w_index 2
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 0   0   954742 7000 1596896
	w_speed 755
	w_wng 2 0 512 0
	w_react $0 $c000 $0
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name Rally Point A

	w_index 3
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 1   0   895466 1000 1623991
	w_speed 1012
	w_wng 1 0 512 0
	w_react $0 $c000 $0
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name Approach Target

	w_index 4
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 1   0   881615 1000 1648534
	w_speed 1012
	w_wng 1 0 2048 0
	w_react $740 $c000 $1800
	w_searchDist 5
	w_preferredTargetId2 $0
	w_name Attack Camp

	w_index 5
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 1   0   926084 4000 1675993
	w_speed 1012
	w_wng 1 0 2048 0
	w_react $0 $c000 $1c00
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name Egress

	w_index 6
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 0   0   1167702 7000 1644873
	w_speed 759
	w_wng 1 0 2048 0
	w_react $0 $c000 $1c00
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name Return to Base

	w_index 7
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 1   0   1197105 2000 1658967
	w_speed 590
	w_wng 1 0 2048 0
	w_react $0 $c000 $1c00
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name Landing Approach

	w_index 8
	w_flags $0
	w_goal 34
	w_next 0
	w_pos2 1   0   1198077 0 1687803
	w_speed 421
	w_wng 1 0 2048 0
	w_react $0 $c000 $1c00
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name Land

	w_index 9
	w_flags $2
	w_goal 0
	w_next 0
	w_pos2 0   0   0 0 0
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

  w_for -122
	.

waypoint2 10
	w_index 0
	w_flags $1
	w_goal 0
	w_next 0
	w_pos2 0   0   1203751 0 1693746
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

	w_index 1
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 1   0   1197051 3000 1703642
	w_speed 590
	w_wng 2 0 2048 0
	w_react $c000 $0 $0
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name Take-Off

	w_index 2
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 0   0   954742 7000 1596896
	w_speed 755
	w_wng 2 0 512 0
	w_react $0 $c000 $0
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name Rally Point A

	w_index 3
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 1   0   895466 1000 1623991
	w_speed 1012
	w_wng 1 0 512 0
	w_react $0 $c000 $0
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name Approach Target

	w_index 4
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 1   0   881615 1000 1648534
	w_speed 1012
	w_wng 1 0 2048 0
	w_react $740 $c000 $1800
	w_searchDist 5
	w_preferredTargetId2 $0
	w_name Attack Camp

	w_index 5
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 1   0   926084 4000 1675993
	w_speed 1012
	w_wng 1 0 2048 0
	w_react $0 $c000 $1c00
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name Egress

	w_index 6
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 0   0   1167702 7000 1644873
	w_speed 759
	w_wng 1 0 2048 0
	w_react $0 $c000 $1c00
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name Return to Base

	w_index 7
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 1   0   1197105 2000 1658967
	w_speed 590
	w_wng 1 0 2048 0
	w_react $0 $c000 $1c00
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name Landing Approach

	w_index 8
	w_flags $0
	w_goal 34
	w_next 0
	w_pos2 1   0   1198077 0 1687803
	w_speed 421
	w_wng 1 0 2048 0
	w_react $0 $c000 $1c00
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name Land

	w_index 9
	w_flags $2
	w_goal 0
	w_next 0
	w_pos2 0   0   0 0 0
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

  w_for -123
	.

waypoint2 6
	w_index 0
	w_flags $1
	w_goal 0
	w_next 0
	w_pos2 0   0   1479433 26000 1520065
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

	w_index 1
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 0   0   1222016 26000 2010910
	w_speed 457
	w_wng 1 0 2048 0
	w_react $c000 $0 $0
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name Waypoint 1

	w_index 2
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 0   0   795551 26000 1936723
	w_speed 457
	w_wng 1 0 2048 0
	w_react $0 $0 $c000
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name Waypoint 2

	w_index 3
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 1   0   692762 2000 1933989
	w_speed 457
	w_wng 1 0 2048 0
	w_react $0 $0 $c000
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name Approach Landing

	w_index 4
	w_flags $0
	w_goal 34
	w_next 0
	w_pos2 1   0   691668 0 1967341
	w_speed 457
	w_wng 1 0 2048 0
	w_react $0 $0 $c000
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name Land

	w_index 5
	w_flags $2
	w_goal 0
	w_next 0
	w_pos2 0   0   0 0 0
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

  w_for -128
	.

waypoint2 10
	w_index 0
	w_flags $1
	w_goal 0
	w_next 0
	w_pos2 0   0   1203751 0 1693746
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

	w_index 1
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 1   0   1197051 3000 1703642
	w_speed 590
	w_wng 2 0 2048 0
	w_react $c000 $0 $0
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name Take-Off

	w_index 2
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 0   0   954742 7000 1596896
	w_speed 755
	w_wng 2 0 512 0
	w_react $0 $c000 $0
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name Rally Point A

	w_index 3
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 1   0   895466 1000 1623991
	w_speed 1012
	w_wng 1 0 512 0
	w_react $0 $c000 $0
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name Approach Target

	w_index 4
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 1   0   881615 1000 1648534
	w_speed 1012
	w_wng 1 0 2048 0
	w_react $740 $c000 $1800
	w_searchDist 5
	w_preferredTargetId2 $0
	w_name Attack Camp

	w_index 5
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 1   0   926084 4000 1675993
	w_speed 1012
	w_wng 1 0 2048 0
	w_react $0 $c000 $1c00
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name Egress

	w_index 6
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 0   0   1167702 7000 1644873
	w_speed 759
	w_wng 1 0 2048 0
	w_react $0 $c000 $1c00
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name Return to Base

	w_index 7
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 1   0   1197105 2000 1658967
	w_speed 590
	w_wng 1 0 2048 0
	w_react $0 $c000 $1c00
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name Landing Approach

	w_index 8
	w_flags $0
	w_goal 34
	w_next 0
	w_pos2 1   0   1198077 0 1687803
	w_speed 421
	w_wng 1 0 2048 0
	w_react $0 $c000 $1c00
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name Land

	w_index 9
	w_flags $2
	w_goal 0
	w_next 0
	w_pos2 0   0   0 0 0
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

  w_for -133
	.

waypoint2 10
	w_index 0
	w_flags $1
	w_goal 0
	w_next 0
	w_pos2 0   0   1203751 0 1693746
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

	w_index 1
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 1   0   1197051 3000 1703642
	w_speed 590
	w_wng 2 0 2048 0
	w_react $c000 $0 $0
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name Take-Off

	w_index 2
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 0   0   954742 7000 1596896
	w_speed 755
	w_wng 2 0 512 0
	w_react $0 $c000 $0
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name Rally Point A

	w_index 3
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 1   0   895466 1000 1623991
	w_speed 1012
	w_wng 1 0 512 0
	w_react $0 $c000 $0
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name Approach Target

	w_index 4
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 1   0   881615 1000 1648534
	w_speed 1012
	w_wng 1 0 2048 0
	w_react $740 $c000 $1800
	w_searchDist 5
	w_preferredTargetId2 $0
	w_name Attack Camp

	w_index 5
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 1   0   926084 4000 1675993
	w_speed 1012
	w_wng 1 0 2048 0
	w_react $0 $c000 $1c00
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name Egress

	w_index 6
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 0   0   1167702 7000 1644873
	w_speed 759
	w_wng 1 0 2048 0
	w_react $0 $c000 $1c00
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name Return to Base

	w_index 7
	w_flags $0
	w_goal 1
	w_next 0
	w_pos2 1   0   1197105 2000 1658967
	w_speed 590
	w_wng 1 0 2048 0
	w_react $0 $c000 $1c00
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name Landing Approach

	w_index 8
	w_flags $0
	w_goal 34
	w_next 0
	w_pos2 1   0   1198077 0 1687803
	w_speed 421
	w_wng 1 0 2048 0
	w_react $0 $c000 $1c00
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name Land

	w_index 9
	w_flags $2
	w_goal 0
	w_next 0
	w_pos2 0   0   0 0 0
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

  w_for -134
	.

waypoint2 4
	w_index 0
	w_flags $1
	w_goal 0
	w_next 0
	w_pos2 0   0   1052346 0 1632973
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

	w_index 1
	w_flags $4
	w_goal 1
	w_next 0
	w_pos2 1   0   1050834 0 1638228
	w_speed 50
	w_wng 1 0 2048 0
	w_react $3fff $c000 $0
	w_searchDist 10
	w_preferredTargetId2 $ff76
	w_name 

	w_index 2
	w_flags $4
	w_goal 1
	w_next 0
	w_pos2 1   0   1053570 0 1630454
	w_speed 50
	w_wng 1 0 2048 0
	w_react $3fff $c000 $0
	w_searchDist 10
	w_preferredTargetId2 $ff76
	w_name 

	w_index 3
	w_flags $2
	w_goal 0
	w_next 0
	w_pos2 0   0   0 0 0
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

  w_for -135
	.

waypoint2 3
	w_index 0
	w_flags $1
	w_goal 0
	w_next 0
	w_pos2 0   0   1056953 0 1627070
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

	w_index 1
	w_flags $4
	w_goal 1
	w_next 0
	w_pos2 1   0   1052850 0 1637076
	w_speed 33
	w_wng 1 0 2048 0
	w_react $ffff $0 $0
	w_searchDist 10
	w_preferredTargetId2 $ff76
	w_name 

	w_index 2
	w_flags $2
	w_goal 0
	w_next 0
	w_pos2 0   0   0 0 0
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

  w_for -136
	.

waypoint2 4
	w_index 0
	w_flags $1
	w_goal 0
	w_next 0
	w_pos2 0   0   1055657 0 1634269
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

	w_index 1
	w_flags $4
	w_goal 1
	w_next 0
	w_pos2 1   0   1052994 0 1638156
	w_speed 50
	w_wng 1 0 2048 0
	w_react $3fff $c000 $0
	w_searchDist 10
	w_preferredTargetId2 $0
	w_name 

	w_index 2
	w_flags $4
	w_goal 1
	w_next 0
	w_pos2 1   0   1057673 0 1633621
	w_speed 16
	w_wng 1 0 2048 0
	w_react $3fff $c000 $0
	w_searchDist 10
	w_preferredTargetId2 $ff75
	w_name 

	w_index 3
	w_flags $2
	w_goal 0
	w_next 0
	w_pos2 0   0   0 0 0
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

  w_for -137
	.

waypoint2 3
	w_index 0
	w_flags $1
	w_goal 0
	w_next 0
	w_pos2 0   0   1051554 0 1636141
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

	w_index 1
	w_flags $4
	w_goal 1
	w_next 0
	w_pos2 1   0   1055009 0 1631821
	w_speed 50
	w_wng 1 0 2048 0
	w_react $ffff $0 $0
	w_searchDist 10
	w_preferredTargetId2 $ff79
	w_name 

	w_index 2
	w_flags $2
	w_goal 0
	w_next 0
	w_pos2 0   0   0 0 0
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

  w_for -138
	.

waypoint2 3
	w_index 0
	w_flags $1
	w_goal 0
	w_next 0
	w_pos2 0   0   1055729 0 1638588
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

	w_index 1
	w_flags $4
	w_goal 1
	w_next 0
	w_pos2 1   0   1058465 0 1635493
	w_speed 50
	w_wng 1 0 2048 0
	w_react $ffff $0 $0
	w_searchDist 10
	w_preferredTargetId2 $0
	w_name 

	w_index 2
	w_flags $2
	w_goal 0
	w_next 0
	w_pos2 0   0   0 0 0
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

  w_for -139
	.

waypoint2 3
	w_index 0
	w_flags $1
	w_goal 0
	w_next 0
	w_pos2 0   0   1061776 0 1628654
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

	w_index 1
	w_flags $4
	w_goal 1
	w_next 0
	w_pos2 1   0   1054145 0 1637364
	w_speed 50
	w_wng 1 0 2048 0
	w_react $3fff $c000 $0
	w_searchDist 10
	w_preferredTargetId2 $ff75
	w_name 

	w_index 2
	w_flags $2
	w_goal 0
	w_next 0
	w_pos2 0   0   0 0 0
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

  w_for -140
	.

waypoint2 3
	w_index 0
	w_flags $1
	w_goal 0
	w_next 0
	w_pos2 0   0   1047379 0 1640532
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

	w_index 1
	w_flags $4
	w_goal 1
	w_next 0
	w_pos2 1   0   1058752 0 1628438
	w_speed 50
	w_wng 1 0 2048 0
	w_react $c000 $0 $0
	w_searchDist 25
	w_preferredTargetId2 $ff78
	w_name 

	w_index 2
	w_flags $2
	w_goal 0
	w_next 0
	w_pos2 0   0   0 0 0
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

  w_for -141
	.

waypoint2 3
	w_index 0
	w_flags $1
	w_goal 0
	w_next 0
	w_pos2 0   0   1049251 0 1641035
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

	w_index 1
	w_flags $4
	w_goal 1
	w_next 0
	w_pos2 1   0   1053570 0 1627574
	w_speed 50
	w_wng 1 0 2048 0
	w_react $c000 $0 $0
	w_searchDist 25
	w_preferredTargetId2 $ff79
	w_name 

	w_index 2
	w_flags $2
	w_goal 0
	w_next 0
	w_pos2 0   0   0 0 0
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

  w_for -142
	.

waypoint2 3
	w_index 0
	w_flags $1
	w_goal 0
	w_next 0
	w_pos2 0   0   1052058 0 1641035
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

	w_index 1
	w_flags $4
	w_goal 1
	w_next 0
	w_pos2 1   0   1056233 0 1631030
	w_speed 50
	w_wng 1 0 2048 0
	w_react $c000 $0 $0
	w_searchDist 25
	w_preferredTargetId2 $ff77
	w_name 

	w_index 2
	w_flags $2
	w_goal 0
	w_next 0
	w_pos2 0   0   0 0 0
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

  w_for -143
	.

waypoint2 4
	w_index 0
	w_flags $1
	w_goal 0
	w_next 0
	w_pos2 0   0   1203208 0 1691189
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

	w_index 1
	w_flags $4
	w_goal 1
	w_next 0
	w_pos2 1   0   1203304 0 1686585
	w_speed 50
	w_wng 1 0 2048 0
	w_react $c000 $0 $0
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name 

	w_index 2
	w_flags $4
	w_goal 1
	w_next 0
	w_pos2 1   0   1195393 0 1686633
	w_speed 33
	w_wng 1 0 2048 0
	w_react $c000 $0 $0
	w_searchDist 25
	w_preferredTargetId2 $0
	w_name 

	w_index 3
	w_flags $2
	w_goal 0
	w_next 0
	w_pos2 0   0   0 0 0
	w_speed 0
	w_wng 0 0 0 0
	w_react $0 $0 $0
	w_searchDist 0
	w_preferredTargetId2 $0
	w_name 

  w_for -154
	.

 