#include <catch2/catch_test_macros.hpp>
#include "assets/icons_baked.h"

#include <string>
#include <vector>

// The baked icon data (gui/src/assets/icons_baked.cpp) is generated by
// tools/gen_icons.py; the generator's currency is enforced separately by the
// gen_icons_currency ctest. These cover the committed data's shape and the
// C++ accessors — no GL context, so they run in the display-free gui_tests.

using namespace fxs::icons;

TEST_CASE("baked icon set covers every category at both sizes", "[gui][icons]") {
    REQUIRE(Count == 9);
    for (int i = 0; i < Count; ++i) {
        Id id = static_cast<Id>(i);
        INFO("icon " << i << " = " << (Name(id) ? Name(id) : "(null)"));
        REQUIRE(Name(id) != nullptr);

        const Coverage& s = Get(id, 24);
        const Coverage& l = Get(id, 48);
        CHECK(s.size == 24);
        CHECK(l.size == 48);
        REQUIRE(s.a8 != nullptr);
        REQUIRE(l.a8 != nullptr);

        long coverage = 0;
        for (int p = 0; p < s.size * s.size; ++p) coverage += s.a8[p];
        CHECK(coverage > 0);        // a non-empty glyph
        CHECK(s.a8[0] == 0);        // corner padding stays clear
    }
}

TEST_CASE("Get selects the nearest baked size", "[gui][icons]") {
    CHECK(Get(Id::Aircraft, 16).size == 24);
    CHECK(Get(Id::Aircraft, 24).size == 24);
    CHECK(Get(Id::Aircraft, 25).size == 48);
    CHECK(Get(Id::Aircraft, 48).size == 48);
}

TEST_CASE("ToRgba yields white with coverage in alpha", "[gui][icons]") {
    const Coverage& c = Get(Id::Terrain, 24);
    std::vector<uint8_t> rgba((size_t)c.size * c.size * 4);
    ToRgba(c, rgba.data());
    for (int p = 0; p < c.size * c.size; ++p) {
        CHECK(rgba[p * 4 + 0] == 255);
        CHECK(rgba[p * 4 + 1] == 255);
        CHECK(rgba[p * 4 + 2] == 255);
        CHECK(rgba[p * 4 + 3] == c.a8[p]);
    }
}

TEST_CASE("icon names match the SVG source basenames", "[gui][icons]") {
    CHECK(std::string(Name(Id::Aircraft)) == "aircraft");
    CHECK(std::string(Name(Id::ArtUI)) == "art-ui");
    CHECK(std::string(Name(Id::Archives)) == "archives");
}
