// Generated by tools/gen_icons.py. Do not edit.
#pragma once
#include <cstdint>

namespace fxs::icons {

enum class Id { Aircraft, Vehicles, Weapons, Missions, Campaigns, Terrain, Audio, ArtUI, Archives, Count };
inline constexpr int Count = static_cast<int>(Id::Count);

// One baked size variant: `size`x`size` 8-bit coverage. The glyph is
// monochrome, so RGB is white by construction and only `a8` (alpha)
// is stored; expand with ToRgba() before uploading, then tint per theme.
struct Coverage { int size; const uint8_t* a8; };

// Baked variant nearest the requested pixel size (24 or 48).
const Coverage& Get(Id id, int px);
// Stable lower-case identifier, matching the SVG source basename.
const char* Name(Id id);
// Expand coverage to RGBA8 (white, coverage in alpha) into `dst`,
// which must hold cov.size*cov.size*4 bytes.
void ToRgba(const Coverage& cov, uint8_t* dst);

} // namespace fxs::icons
