#!/usr/bin/env python3
"""Generate fxe's C++ declarations from db/ (#459, epic #280).

fxe is the executable-level analogue of the fx_lib/fx/fxs validation layer: where a
byte-identical codec proves a *format* is understood, a runnable source port proves the
*game-executable reconstruction*. This is its first stage -- the generator that turns the
symbol database into C++.

    python3 tools/gen_fxe.py --write       # emit fxe/generated/
    python3 tools/gen_fxe.py --check       # CI: regenerate and diff (currency)
    python3 tools/gen_fxe.py --self-test   # unit tests, no db/ needed

THE GENERATOR IS THE SOURCE OF TRUTH; THE EMITTED C++ IS COMMITTED
-----------------------------------------------------------------
Per #280, the tooling lives in the repo and the generated source is checked in and kept in
sync by CI -- the same pattern as the generated status matrices. Nothing under
fxe/generated/ is ever hand-edited.

CLEAN-ROOM (ADR-0002)
---------------------
Every declaration here is derived from facts WE recovered -- db/symbols/, db/types/ -- and
from our own prose. Nothing is transcribed from decompiler output or from OpenFA.

WHAT IT EMITS, AND WHAT IT REFUSES TO INVENT
--------------------------------------------
The reconstruction is incomplete, and the generated tree says so out loud rather than
papering over it:

  * A function whose signature is recovered becomes a real declaration.
  * A function whose signature is NOT recovered becomes a `TODO(#453)` line naming it and
    its address -- NOT a guessed `void f()`. A wrong prototype would compile and then lie.
  * `undefinedN` is preserved verbatim: it means "N bytes, type not recovered" (#452/#455),
    and flattening it into `int`/`u32` would invent semantics the evidence never proved.

Calling conventions are dropped from the declarations and kept as provenance comments: they
are an artifact of a 32-bit x86 ABI, and fxe is a modern 64-bit port where they mean nothing.
The convention still matters to db/ (it is a recovered fact) -- just not to the emitted code.
"""

import argparse
import csv
import difflib
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
DB = REPO / "db"
OUT = REPO / "fxe" / "generated"

BANNER = """\
// GENERATED by tools/gen_fxe.py from db/ -- DO NOT EDIT.
//
// Clean-room (ADR-0002): derived from the symbol database this project recovered, never
// transcribed from decompiler output. Regenerate with `python3 tools/gen_fxe.py --write`.
"""

CONVENTIONS = ("__cdecl", "__stdcall", "__fastcall", "__thiscall", "__pascal")

# A subsystem slug is not a C++ identifier ("flight-model", "comms-dl").
def ns(slug):
    return slug.replace("-", "_")


def binary_ns(binary):
    """FA.EXE -> fa, WAIL32.DLL -> wail32, CDRVDL32.DLL -> cdrvdl32."""
    return re.sub(r"\W", "_", binary.split(".")[0]).lower()


def strip_convention(proto):
    """Drop EVERY MSVC calling convention from a stored prototype -> (proto, own_convention).

    Conventions are an artifact of the 32-bit x86 ABI; fxe is a modern 64-bit port, where
    `__cdecl` is not even a keyword -- gcc and clang reject it outright. They are dropped from
    the emitted code and kept as provenance comments; db/ remains their home, because there
    the convention is a recovered fact (#452 proved it from the decoration).

    That includes the conventions nested inside FUNCTION-POINTER PARAMETERS. They are no more
    portable than the outer one, and an earlier version of this generator kept them -- the
    compile check rejected it, which is precisely what the compile check is for.

    The returned convention is the FUNCTION'S OWN: the one before its parameter list.
    """
    lp = proto.find("(")
    head = proto[:lp] if lp >= 0 else proto
    own = next((c for c in CONVENTIONS if c in head), "")
    out = proto
    for c in CONVENTIONS:
        out = out.replace(c, " ")
    return re.sub(r"\s+", " ", out).replace("( ", "(").replace(" )", ")").strip(), own


def proto_ident(proto):
    """The function's own name: the last identifier before its parameter list."""
    head = proto.split("(", 1)[0]
    idents = re.findall(r"[A-Za-z_]\w*", head)
    return idents[-1] if idents else ""


def undecorate(name):
    """A C++ identifier for a decorated symbol: `_foo@4` -> foo, `?bar@@3DA` -> bar."""
    m = re.match(r"^\?([A-Za-z_]\w*)@@", name)
    if m:
        return m.group(1)
    m = re.match(r"^[_@]?([A-Za-z_]\w*?)(@\d+)?$", name)
    return m.group(1) if m else re.sub(r"\W", "_", name)


def load():
    subs = []
    with open(DB / "subsystems.csv", encoding="utf-8", newline="") as fh:
        subs = list(csv.DictReader(fh))
    syms = {}
    for s in subs:
        p = DB / "symbols" / ("%s.csv" % s["slug"])
        if not p.exists():
            continue
        with open(p, encoding="utf-8", newline="") as fh:
            syms[s["slug"]] = [r for r in csv.DictReader(fh) if r["source"] != "waiver"]
    return subs, syms


def emit_types():
    """The type header: db/types/fa_types.h, materialized as C++ with asserted sizes.

    db/types/ stays canonical -- this is a materialization of it, not a second copy to be
    maintained. The static_asserts are the point: they turn the recovered sizes into a claim
    the compiler checks on every build, so a layout that drifts stops the build instead of
    silently miscompiling the port.
    """
    body = (DB / "types" / "fa_types.h").read_text(encoding="utf-8")
    out = [BANNER, "#pragma once", "", "#include <cstddef>", "", "namespace fxe {", ""]
    out.append("// --- from db/types/fa_types.h ---------------------------------------")
    out.append(body.rstrip())
    out.append("")
    out.append("// The recovered widths, asserted. A scalar that is not the size db/ says it")
    out.append("// is would miscompile every access the port makes through it.")
    for t, n in [("u8", 1), ("s8", 1), ("u16", 2), ("s16", 2), ("u32", 4), ("s32", 4),
                 ("fixed24", 4), ("undefined1", 1), ("undefined2", 2), ("undefined4", 4)]:
        out.append("static_assert(sizeof(%s) == %d, \"%s must be %d byte(s)\");" % (t, n, t, n))
    out.append("")
    out.append("// The recovered LAYOUTS, asserted (#454). Each size is a claim the code proves:")
    out.append("//   entity   0xDE  -- the common region of every object record. The record itself")
    out.append("//                     is variable-size (0xDE + type->obj_ext_size), so this is the")
    out.append("//                     shared part, not the whole object: OBJAdd and GetCurObj both")
    out.append("//                     compute the total the same way, independently.")
    out.append("//   OBJ_TYPE 0x81  -- the common HEADER of the type record; its total size is")
    out.append("//                     self-declared at +0x01, and the class extension follows.")
    out.append("//   CN_INFO  0xDDC -- the config body CN_ReadConfig reads.")
    out.append("// The per-class extensions stay opaque on purpose: they all begin at the same")
    out.append("// offset, so their fields alias, and a named one would be a guess (#454).")
    for t, n, why in [("entity", 0xDE, "the common region of an object record"),
                      ("OBJ_TYPE", 0x81, "the common header of a type record"),
                      ("CN_INFO", 0xDDC, "a 0xDDC-byte config body")]:
        out.append("static_assert(sizeof(%s) == 0x%X, \"%s is %s\");" % (t, n, t, why))
    out.append("")
    out.append("}  // namespace fxe")
    return "\n".join(out) + "\n"


def emit_subsystem(sub, rows):
    slug, binary = sub["slug"], sub["binary"]
    funcs = [r for r in rows if r["kind"] == "func"]
    data = [r for r in rows if r["kind"] == "data"]
    signed = [r for r in funcs if r["type"].strip()]
    unsigned = [r for r in funcs if not r["type"].strip()]
    typed = [r for r in data if r["type"].strip()]
    untyped = [r for r in data if not r["type"].strip()]

    o = [BANNER, "#pragma once", "", '#include "../fa_types.hpp"', "",
         "// %s -- %s" % (sub["title"], binary),
         "// %d/%d functions have a recovered signature; %d/%d globals have a recovered type."
         % (len(signed), len(funcs), len(typed), len(data)),
         "",
         "namespace fxe::%s::%s {" % (binary_ns(binary), ns(slug)), ""]

    if typed:
        o.append("// --- globals ---------------------------------------------------------")
        for r in typed:
            ident = undecorate(r["display"].strip() or r["name"])
            note = (r["notes"] or "").strip().replace("\n", " ")
            o.append("extern %s %s;%s" % (r["type"].strip(), ident,
                                          ("  // %s  %s" % (r["va"], note)).rstrip()))
        o.append("")

    if signed:
        o.append("// --- functions -------------------------------------------------------")
        for r in signed:
            proto, conv = strip_convention(r["type"].strip())
            o.append("%s;  // %s%s" % (proto, r["va"], "  " + conv if conv else ""))
        o.append("")

    # The reconstruction's remaining debt, stated in the generated source rather than hidden.
    # A guessed `void f()` would compile and then lie; a TODO cannot.
    if unsigned or untyped:
        o.append("// --- not yet recovered -----------------------------------------------")
        o.append("// Emitted as TODOs, not as guessed declarations: a wrong prototype would")
        o.append("// compile and then lie about what the original function took.")
        for r in unsigned:
            o.append("// TODO(#453): %s  %s -- signature not recovered"
                     % (r["va"], r["display"].strip() or r["name"]))
        for r in untyped:
            o.append("// TODO(#455): %s  %s -- type not recovered"
                     % (r["va"], r["display"].strip() or r["name"]))
        o.append("")

    o.append("}  // namespace fxe::%s::%s" % (binary_ns(binary), ns(slug)))
    return "\n".join(o) + "\n"


def emit_root(subs):
    o = [BANNER, "#pragma once", "", "#include \"fa_types.hpp\"", ""]
    for s in subs:
        o.append('#include "subsystems/%s.hpp"' % s["slug"])
    o.append("")
    o.append("// Every declaration fxe has recovered so far. Including this header is what the")
    o.append("// build compiles: a declaration that is not valid C++ is not a reconstruction.")
    return "\n".join(o) + "\n"


def generate():
    subs, syms = load()
    files = {"fa_types.hpp": emit_types(), "fxe.hpp": emit_root(subs)}
    for s in subs:
        rows = syms.get(s["slug"], [])
        files["subsystems/%s.hpp" % s["slug"]] = emit_subsystem(s, rows)
    return files


def write(files):
    for rel, text in files.items():
        p = OUT / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        # newline="\n" and an explicit encoding, so the emitted bytes are identical on
        # every platform. Text mode would translate "\n" to CRLF on Windows, and the
        # locale default would decode the em-dashes in db/'s notes as cp1252 -- either one
        # makes the committed C++ "drift" the moment it is regenerated on another machine.
        # (It did: the MSVC leg of CI caught exactly that.)
        with open(p, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
    return len(files)


def check(files):
    errs = []
    for rel, text in sorted(files.items()):
        p = OUT / rel
        if not p.exists():
            errs.append("fxe/generated/%s is missing; run `python3 tools/gen_fxe.py --write`"
                        % rel)
            continue
        have = p.read_text(encoding="utf-8")
        if have != text:
            diff = "\n".join(list(difflib.unified_diff(
                have.splitlines(), text.splitlines(),
                fromfile="committed", tofile="regenerated", lineterm=""))[:12])
            errs.append("fxe/generated/%s is stale (db/ changed but the generated C++ did "
                        "not):\n%s" % (rel, diff))
    if OUT.is_dir():
        for p in sorted(OUT.rglob("*.hpp")):
            rel = p.relative_to(OUT).as_posix()
            if rel not in files:
                errs.append("fxe/generated/%s is not generated by db/ -- a stale file, or a "
                            "hand-edit" % rel)
    return errs


# --- self-test ---------------------------------------------------------------------
def self_test():
    fails = []
    for proto, want_p, want_c in [
        ("char __fastcall COLFlatGround(long, F24_POINT3 *)",
         "char COLFlatGround(long, F24_POINT3 *)", "__fastcall"),
        ("undefined4 __stdcall CTInit(void)", "undefined4 CTInit(void)", "__stdcall"),
        # A function-pointer parameter's own convention must ALSO go: gcc and clang do not
        # know `__stdcall`, so keeping it emits a header that will not compile. (It did, once
        # -- the compile check caught it.) The reported convention stays the OUTER one.
        ("int __cdecl _ValidateExecute(int (__stdcall *)(void))",
         "int _ValidateExecute(int (*)(void))", "__cdecl"),
    ]:
        got_p, got_c = strip_convention(proto)
        if got_p != want_p or got_c != want_c:
            fails.append("  strip_convention(%r) -> %r/%r, want %r/%r"
                         % (proto, got_p, got_c, want_p, want_c))

    for proto, want in [("char __fastcall COLFlatGround(long, F24_POINT3 *)", "COLFlatGround"),
                        ("undefined4 CTInit(void)", "CTInit"),
                        ("int f(int (*)(void))", "f")]:
        if proto_ident(proto) != want:
            fails.append("  proto_ident(%r) -> %r, want %r" % (proto, proto_ident(proto), want))

    for name, want in [("_InitJoysticks@0", "InitJoysticks"), ("@ReadSticksRaw@0", "ReadSticksRaw"),
                       ("?mm_initialized@@3DA", "mm_initialized"), ("NETSlaveConnect",
                                                                    "NETSlaveConnect"),
                       ("_CTVarDiff", "CTVarDiff")]:
        if undecorate(name) != want:
            fails.append("  undecorate(%r) -> %r, want %r" % (name, undecorate(name), want))

    if ns("flight-model") != "flight_model":
        fails.append("  a slug is not a C++ identifier: flight-model")
    if binary_ns("WAIL32.DLL") != "wail32" or binary_ns("FA.EXE") != "fa":
        fails.append("  binary_ns wrong")

    if fails:
        print("gen_fxe self-test FAILED:\n" + "\n".join(fails))
        return 1
    print("gen_fxe self-test: %d cases OK" % 13)
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--write", action="store_true")
    g.add_argument("--check", action="store_true")
    g.add_argument("--self-test", action="store_true")
    args = ap.parse_args()

    if args.self_test:
        return self_test()

    files = generate()
    if args.write:
        n = write(files)
        subs, syms = load()
        sf = sum(1 for rows in syms.values() for r in rows
                 if r["kind"] == "func" and r["type"].strip())
        tf = sum(1 for rows in syms.values() for r in rows if r["kind"] == "func")
        tg = sum(1 for rows in syms.values() for r in rows
                 if r["kind"] == "data" and r["type"].strip())
        print("gen_fxe: wrote %d headers to fxe/generated/" % n)
        print("         %d/%d functions declared, %d globals declared; the rest are TODOs "
              "naming what the reconstruction still owes" % (sf, tf, tg))
        return 0

    errs = check(files)
    for e in errs:
        print("error: %s" % e)
    print("gen_fxe --check: %d generated headers, %d error(s)" % (len(files), len(errs)))
    return 1 if errs else 0


if __name__ == "__main__":
    sys.exit(main())
